# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-06 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('career', models.CharField(max_length=70)),
                ('study_plan', models.CharField(max_length=20)),
            ],
        ),
    ]
